### ISSUE TITLE
Metrics tracking and dashboard visualizing required

### ISSUE THREAD

**Issue by trinhdn2** [BuildOnViction/victionchain#430]
Currently we don't have a monitoring dashboard of a single Viction node. This dashboard will not only help monitoring metrics, resource spikes and alerts on the fly but also help evaluating our performance updates and bug fixes, to judge if the updates actually brings a performance change or resolves resource leaking overtime, etc.

The first step of implementing a monitoring dashboard like this is put metrics gauges/meters/counters in code where we want to measure. After that, we need to fetch those metrics and index those in a timeseries database like Prometheus or InfluxDB, as data sources for a visualize platform like Grafana.

Checklist:
- [ ] Update metrics package with Prometheus and InfluxDB support: https://github.com/BuildOnViction/tomochain/pull/428
- [ ] Apply metrics in code
- [ ] Visualize timeseries data on Grafana dashboards

**Comment by abbaahmad** [comment]
Hi. Just to confirm, the binary currently doesn't export metrics and there is no dashboard, right?
